name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        include-prerelease: True
    - name: Restore dependencies
      run: dotnet restore

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Installing Dependencies AspNetCoreIdentityFido2Mfa
      working-directory: AspNetCoreIdentityFido2Mfa
      run: sudo npm install

    - name: Installing Dependencies AspNetCoreIdentityFido2Passwordless
      working-directory: AspNetCoreIdentityFido2Passwordless
      run: sudo npm install

    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
